# permissions for end users to view nodemetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodemetric-viewer-role
rules:
- apiGroups:
  - slo.kooperator
  resources:
  - nodemetrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - slo.kooperator
  resources:
  - nodemetrics/status
  verbs:
  - get
